name: Update patches

on:
  schedule:
    - cron: '0 16 * * *'  # 每天的0点（+8时区）运行
  workflow_dispatch:  # 允许手动触发

jobs:
  update-patches:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [ipq60xx-devel, ipq60xx-devel_nss]
        target-path: [qualcommax/patches-6.6, qualcommax/patches-6.6-nss]
        include:
          - branch: ipq60xx-devel
            target-path: qualcommax/patches-6.6
          - branch: ipq60xx-devel_nss
            target-path: qualcommax/patches-6.6-nss

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Clone source repository
        run: git clone --depth 1 --branch ${{ matrix.branch }} https://github.com/JiaY-shi/openwrt.git source_repo

      - name: Copy patches
        run: |
            rm -rf ${{ matrix.target-path }} || true
            mkdir -p ${{ matrix.target-path }}
            cp -r source_repo/target/linux/qualcommax/patches-6.6/. ${{ matrix.target-path }}
            ls -la ${{ matrix.target-path }}  # 输出目标路径下的文件列表，用于调试

      - name: Check for changes
        id: changes
        run: |
          if git diff --quiet; then
            echo "::set-output name=changes::false"
          else
            echo "::set-output name=changes::true"
          fi

      - name: Commit and push changes
        if: steps.changes.outputs.changes == 'true'
        run: |
          git config user.email "github-actions@github.com"
          git config user.name "GitHub Actions"

          git add ${{ matrix.target-path }}
          git commit -m "Update patches from ${{ matrix.branch }} on $(date +'%Y-%m-%d')"
           git push --force origin HEAD:main
